nss-day-cohort-44/nutshell-whistling-wraiths

- src/index.html
> some basic html

- src/scripts/Nutshell.js
- src/scripts/user/UserDataProvider.js
Wrote functions to fetch the users from json, parse them into js and store them in a variable which can be called in other modules.
git checkout mc-userProvider
navigate to the UserDataProvider module in the User directory and verify the code is present.
- [ x] I have added test instructions that prove my fix is effective or that my feature works
> Mc user provider

- src/scripts/Nutshell.js
- src/scripts/message/Message.js
- src/scripts/message/MessageDataProvider.js
- src/scripts/message/MessageForm.js
- src/scripts/message/MessageList.js
You can delete messages when you are the sender
hit delete next to the message
> Dw delete messages

- src/scripts/Nutshell.js
- src/scripts/message/MessageDataProvider.js
- src/scripts/message/MessageForm.js
- src/scripts/message/MessageList.js
You can now type in a message and it will render to the dom 
Type in a new message and click post. It will then render your message to the dom and clear the form for another message
- [ X] My code follows the style guidelines of this project
- [ X] I have performed a self-review of my own code
- [ X] I have commented my code, particularly in hard-to-understand areas
- [ X] My changes generate no new warnings or errors
- [ X] I have added test instructions that prove my fix is effective or that my feature works
> saving messages

- src/scripts/Nutshell.js
- src/styles/main.css
> some styling has been applied

- src/scripts/Nutshell.js
- src/scripts/articles/ArticleForm.js
- src/scripts/events/Event.js
- src/scripts/events/EventDataProvider.js
- src/scripts/events/EventForm.js
- src/scripts/events/EventList.js
Made events for the current user display and have basic CRUD functionality
Test it by adding/deleting an event with the buttons
> Events now exist on the DOM and have basic CRUD functionality

- src/scripts/message/Message.js
- src/scripts/message/MessageDataProvider.js
- src/scripts/message/MessageForm.js
- src/scripts/message/MessageList.js
You can now edit messages
first create a new message to make sure that is still working.
then pick a message to edit. click the edit button. type in some new text. and click post again. 
- [ X] My code follows the style guidelines of this project
- [ X] I have performed a self-review of my own code
- [ X] I have commented my code, particularly in hard-to-understand areas
- [ X] My changes generate no new warnings or errors
- [ X] I have added test instructions that prove my fix is effective or that my feature works
> Dw editing messages

- src/scripts/Nutshell.js
- src/scripts/events/EventList.js
- src/scripts/friends/Friend.js
- src/scripts/friends/FriendDataProvider.js
- src/scripts/friends/FriendForm.js
- src/scripts/friends/FriendList.js
This is an update which brings this component closer to MVP, the Friends can be added and deleted from the JSON server and updated live on the DOM
Fixes # (non-functioning "Remove Friend" button)
Log into the Homepage as usual and choose available friends from the friends array from the dropdown menu and click the Save button. check to make sure the Remove buttons are working and updating live
- [x ] My …
> Bs remove friend btn

- src/scripts/events/EventForm.js
- src/scripts/events/EventList.js
Should eliminate issues where issues that would arise when user lacked 2+ events with one in the future.
Please try to break it however you can.
- [ x] I have added test instructions that prove my fix is effective or that my feature works
> Dd event fix

- src/scripts/articles/Article.js
- src/scripts/articles/ArticleList.js
- src/scripts/friends/FriendDataProvider.js
- src/scripts/friends/FriendForm.js
- src/scripts/friends/FriendList.js
The articles box now displays your friend's articles. It also updates as you add or delete friends. 
Make sure you have friends and they have articles. See if they render. Add a friend and delete a friend to make sure that the articles list is keeping up. 
- [ X] My code follows the style guidelines of this project
- [X ] I have performed a self-review of my own code
- [ X] I have commented my code, particularly in hard-to-understand areas
- [ X] My changes generate no new warnings or errors
- [ X] I have added test instructions that prove my fix is effective or that my …
> Dw friends articles

- src/scripts/friends/FriendForm.js
- src/scripts/message/Message.js
We are now able to live populate the friendslist display and the json server by clicking on the names of other users in the message display area
Fixes # (adding friends from message board)
click on the names in bold, test both "Yes" and "No Thanks" button
> Bs add friends from messages

- src/scripts/message/MessageForm.js
you can now send a message using the enter key
type a message and hit enter
> Dw enterpress

- src/scripts/events/Event.js
- src/scripts/events/EventList.js
- src/scripts/friends/FriendList.js
You should now see friends' events
Please ensure friends' events display on the DOM
> Dd friend events

- src/scripts/friends/FriendDataProvider.js
- src/scripts/friends/FriendForm.js
you can only add a friend once
> you can only add a friend once

- src/scripts/articles/Article.js
- src/scripts/events/Event.js
- src/scripts/events/EventList.js
- src/scripts/friends/Friend.js
- src/scripts/friends/FriendForm.js
- src/styles/main.css
basic styling has now been applied as per instructions to the First Event listed as well as to the events and articles of friends
- [ x] My code follows the style guidelines of this project
> Bs friend styling for mvp

- src/scripts/Nutshell.js
- src/scripts/PrivateChat/PrivateChatList.js
- src/scripts/events/EventList.js
- src/scripts/friends/Friend.js
- src/scripts/friends/FriendForm.js
- src/scripts/message/MessageList.js
- src/scripts/message/PrivateChatForm.js
- src/scripts/message/PrivateChatList.js
- src/styles/main.css
You can now send private messages to friends
-click on a friend and click the send private message. Send them some messages. 
-Try logging out and doing it with a few profiles. 
-try deleting and editing (I know editing still has a bug)
- [ X] My code follows the style guidelines of this project
- [ X] I have performed a self-review of my own code
- [ X] I have commented my code, particularly in hard-to-understand areas
- [ X] My changes generate no new warnings or errors
- [ X] I have added test instructions that prove my fix is effective or that my feature works
> Private message

- src/scripts/Nutshell.js
- src/scripts/articles/ArticleList.js
- src/scripts/events/EventList.js
- src/scripts/friends/FriendDataProvider.js
- src/scripts/friends/FriendForm.js
- src/scripts/message/MessageList.js
This update decouples the modules which need to rerender upon a friend being selected and added from the public messages area. FriendList, MessageList, ArticleList, and EventList respond and update live on their own without having to call any other unnecessary rerendering fucntions
Fixes # (too much coupling between the saveFriends and re rendering of the whole page )
- [] New feature (non-breaking change which adds functionality)
- [x ] I have commented my code, …
> Bs add friends fr messages decoupling refactor

- src/scripts/message/Message.js
- src/scripts/message/PrivateChat.js
- src/styles/main.css
double click messages to get the ability to edit or delete them
> Dw styling

- .gitignore
- src/index.html
- src/scripts/articles/Article.js
- src/scripts/articles/ArticleDataProvider.js
- src/scripts/articles/ArticleForm.js
- src/scripts/articles/ArticleList.js
- src/scripts/task/taskForm.js
Made it possible to edit articles
git checkout mc-editArticles
It should have the same functionality as editing tasks.
- [ x] My code follows the style guidelines of this project
> Mc edit articles

- src/styles/main.css
added a min-width to the sections so that flex-wrapping works
serve
use devloper tools to ensure that the elements wrap 
> Mc adding flex wrap

- src/scripts/events/EventForm.js
- src/scripts/events/EventList.js
- src/scripts/events/GeocodeProvider.js
- src/scripts/events/WeatherProvider.js
- src/scripts/events/WeatherSelect.js
Events form now disappears when save edit is clicked, and displays info for currently selected event when you click edit event.
Use the update event functionality and make sure it works
> Dd events cleanup

- src/scripts/events/EventForm.js
- src/scripts/events/EventList.js
- src/scripts/events/GeocodeProvider.js
- src/scripts/events/WeatherProvider.js
- src/scripts/events/WeatherSelect.js
The only functional change this makes is to make sure the city name in forecast is never undefined and is something hyper-specific much less often.  Mostly commenting and refactoring code.
Just spam weather and event options to make sure I didn't break anything.
> Commented and refactored code into easier to read functions

- src/scripts/message/Message.js
- src/scripts/message/PrivateChat.js
The buttons show up when you single click on one of your messages. 
> Dw message bugs

- src/scripts/Nutshell.js
- src/scripts/task/task.js
- src/scripts/task/taskList.js
- src/styles/main.css
Completed tasks should display to the DOM
git checkout mc-completedTasks
serve
check that you can see completed tasks
- [ x] My code follows the style guidelines of this project
> Added a separate area of the tasks column which displays completed tasks

- src/scripts/message/PrivateChat.js
- src/scripts/message/PrivateChatForm.js
- src/scripts/message/PrivateChatList.js
Added a feature for real time chatting
git checkout mc-realTimeChatting
serve
Open two tabs, and log in as a different user for each.
Open the private chat windows with each other.
Try sending messages across both directions.
Ensure that the new messages appear without the user having to type refresh.
- [ x] My code follows the style guidelines of this project
> Mc real time chatting

- src/scripts/Nutshell.js
- src/styles/main.css
> Dw more styling

- src/styles/main.css
check the background for the private messages
> the private messages look like the public ones

- src/scripts/Nutshell.js
- src/scripts/friends/FriendForm.js
- src/scripts/friends/FriendList.js
- src/styles/main.css
Added some nicer styling to the card title headers
Fixes # (ugly titles and lack of capitilization)
JUST LOOK AT IT
> Bs nov19 pre retro

- src/scripts/Nutshell.js
- src/scripts/friends/FriendForm.js
Added a log out
git checkout mc-logOut
serve
check that when you click the log out button, the current user is logged out and presented with the log in/register forms again
> Mc log out

- src/styles/main.css
login page styled Fixes # (issue)
> login page looks nicer

- src/scripts/friends/FriendForm.js
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
> the friend bug is fixed

- src/styles/main.css
just applies a max-height to the logOut button
Fixes # (stying oddness)
- [] New feature (non-breaking change which adds functionality)
- [ x] I have added test instructions that prove my fix is effective or that my feature works
> smaller button for logging out in odd aspect ratios

- src/scripts/message/PrivateChatList.js
- src/styles/main.css
Fixed the private message scroll bar
Now it looks like the public messages
git checkout mc-privateMessageScroll
open a private chat that has enough messages for the scroll bar to generate. Be sure when you reload it starts at the bottom. Click back to friends and verify it still looks right.
> fixed private message scroll bar

- src/scripts/events/WeatherSelect.js
- src/styles/main.css
Weather is more centered
Look at the weather
> Weather center
